// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxcdorrxxtgdokjuqynu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4Y2RvcnJ4eHRnZG9ranVxeW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2NTA0MDcsImV4cCI6MjA4NTIyNjQwN30.aanQ9ABKV6rCcMu1rXggVa0xVUSCJaIXathKXcuN8ik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});